#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。
[project]
id = "aviutl2-font-select-helper"
name = "aviutl2-font-select-helper"
version = "0.1.0"

[development]
aviutl2_version = "latest"

[build_group]
cargo_build_debug = ["cargo build"]
cargo_build_release = ["cargo build --release"]

[artifacts.plugin]
destination = "Plugin/aviutl2_font_select_helper.aux2"
placement_method = "copy"

[artifacts.plugin.profiles.debug]
build = { group = "cargo_build_debug" }
source = "target/debug/aviutl2_font_select_helper.dll"

[artifacts.plugin.profiles.release]
build = { group = "cargo_build_release" }
source = "target/release/aviutl2_font_select_helper.dll"
